# -*- coding: utf-8 -*-
"""Practica 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PFsK5Lw32Kqz-JLICyU4O00todbHgLdG

# PRACTICA 1 - PARTE 1
"""

import tensorflow as tf
import numpy as np


celcius = np.array([-15,-5,0,5,15], dtype=float)
fahrenheit = np.array([5,23,32,41,59], dtype=float)


#capa = tf.keras.layers.Dense(units=1, input_shape=[1])
#modelo = tf.keras.Sequential([capa])
oculta1 = tf.keras.layers.Dense(units=3, input_shape=[1])
oculta2 = tf.keras.layers.Dense(units=3)
salida = tf.keras.layers.Dense(units=1)
modelo = tf.keras.Sequential([oculta1, oculta2, salida])


modelo.compile(
optimizer=tf.keras.optimizers.Adam(0.1),
loss='mean_squared_error'
)


print("comenzando entrenamiento...")
hilstorial=modelo.fit(celcius, fahrenheit, epochs=1000, verbose=False)
print ("modelo entrenado!!!")


import matplotlib.pyplot as plt
plt.xlabel("# Epoca")
plt.ylabel("magnitud de perdida")
plt.plot(hilstorial.history["loss"])


print ("realizar una prediccion")
resultado = modelo.predict ([100.0])
print("El resultado es " + str(resultado)+"°F")

"""# PRÁCTICA 1 - PARTE 2"""

import tensorflow as tf
import numpy as np

litros = np.array([-5,3,1,1,3,5,8], dtype=float)
gal = np.array([-1.32,-0.79,-0.26,0.26,0.79,1.32,2.11], dtype=float)

capa = tf.keras.layers.Dense(units=1, input_shape=[1])
modelo = tf.keras.Sequential([capa])

modelo.compile(
    optimizer = tf.keras.optimizers.Adam(0,1),
    loss='mean_squared_error'
)

print('Comenzando el entrenamiento')
historial = modelo.fit(litros, gal, epochs=1000, verbose=False)
print('Modelo entrenado!')

import matplotlib.pyplot as plt
plt.xlabel("# Epoca")
plt.ylabel("Magnitud de pérdida")
plt.plot(historial.history["loss"])

print("Realizar una predicción!")
resultado = modelo.predict([10])
print("El resultado es..." + str(resultado) + " galones!!")

modelo.save('celcius_a_farenheit.h5')

!ls

pip install tensorflowjs

!mkdir temperatura

!tensorflowjs_converter --input_format keras celcius_fahrenheit.h5 temperatura

!ls temperatura